// Starter catalog, compiled from public sources on 30 Aug 2026 (see
// docs/STUDENTVAULT_MASTER_DOC.md §5). Staff import it from the employee
// console; every row is published straight away and marked "researched", then
// staff re-check it and flip it to "verified" one by one.
//
// Values are deliberately conservative indicative retail values in INR. Perks
// that are free for everyone, or only a discount, count as ₹0 so the headline
// total never oversells.
import type { OfferCategory, OfferStatus } from './types'

export const CATALOG_VERSION = '2026-08-30'
export const CATALOG_RESEARCHED_AT = '2026-08-30T00:00:00.000Z'

export interface CatalogGuide {
  claimSteps: { title: string; body: string }[]
  failureModes: string[]
  proTips: string[]
}

export interface CatalogOffer {
  slug: string
  name: string
  category: OfferCategory
  officialUrl: string
  summary: string
  whatYouGet: string[]
  valueInr: number
  eligibility: string[]
  indiaNote: string
  status: OfferStatus
  statusNote: string
  expiresOn: string | null
  requiresCard: boolean
  autoChargeNote: string
  dependsOn: string[]
  guide?: CatalogGuide
}

type Draft = Pick<CatalogOffer, 'slug' | 'name' | 'category' | 'officialUrl' | 'summary' | 'whatYouGet'> &
  Partial<CatalogOffer>

function offer(d: Draft): CatalogOffer {
  return {
    valueInr: 0,
    eligibility: ['Currently enrolled student'],
    indiaNote: '',
    status: 'live',
    statusNote: '',
    expiresOn: null,
    requiresCard: false,
    autoChargeNote: '',
    dependsOn: [],
    ...d,
  }
}

const GITHUB_PACK = 'github-student-developer-pack'

export const STARTER_CATALOG: CatalogOffer[] = [
  // ── Tier 1 ──────────────────────────────────────────────────────────────
  offer({
    slug: GITHUB_PACK,
    name: 'GitHub Student Developer Pack',
    category: 'IDEs & developer tools',
    officialUrl: 'https://education.github.com/pack',
    summary: 'The master key: one verification unlocks GitHub Pro and 50+ partner offers.',
    whatYouGet: [
      'GitHub Pro while you are a student',
      '50+ partner offers — DigitalOcean, Azure, Namecheap, Heroku, JetBrains and more',
      'GitHub Codespaces hours included with Pro',
      'Verifying here makes several other offers easier to claim',
    ],
    valueInr: 10000,
    eligibility: [
      'Currently enrolled at a degree-granting institution',
      'School-issued email, or a photo of a dated student ID / enrolment proof',
    ],
    indiaNote:
      '.ac.in and .edu.in addresses are often accepted. When they are not, the student-ID photo route works and is the safest default for Indian students.',
    statusNote: 'Free Copilot Pro is no longer part of the pack for new members (paused April 2026).',
    guide: {
      claimSteps: [
        { title: 'Prepare your proof', body: 'Have your college email ready, or a clear photo of your student ID showing your name, college and a current date or validity.' },
        { title: 'Apply from your GitHub account', body: 'Open the official link, sign in, choose “Student”, and add your college from the list.' },
        { title: 'Verify', body: 'Use your college email if you have one. Otherwise take the ID photo in the browser when asked — upload is not allowed, it must be a live photo.' },
        { title: 'Wait for approval', body: 'Approval is usually within a few days. Partner offers appear on the pack page once approved.' },
      ],
      failureModes: [
        'Rejected because the ID has no date — add a bonafide certificate or fee receipt with the current academic year.',
        'Location mismatch — apply from your college or home location, not over a VPN.',
        'Profile name differs from the ID — set your GitHub profile name to match your ID exactly.',
      ],
      proTips: [
        'Claim this first: JetBrains, Azure and DigitalOcean all accept GitHub verification.',
        'Turn on two-factor authentication before applying; it is required.',
      ],
    },
  }),
  offer({
    slug: 'google-ai-plus-students',
    name: 'Google AI Plus — 12 months free for students',
    category: 'AI & LLM tools',
    officialUrl: 'https://blog.google/innovation-and-ai/products/gemini-app/student-offer-google-ai/',
    summary: '12 months of Google AI Plus at no cost for verified students aged 18–24 in India.',
    whatYouGet: [
      'Google AI Plus for 12 months (normally ₹399/month)',
      '400 GB cloud storage',
      'Higher Gemini usage limits',
    ],
    valueInr: 4788,
    eligibility: ['Verified university student', 'Aged 18–24'],
    indiaNote:
      'In India the free 12-month offer is AI Plus, not AI Pro. AI Pro is only offered at a student discount in some markets.',
    expiresOn: '2026-12-31',
    requiresCard: true,
    autoChargeNote:
      'A payment method is required at sign-up and the plan renews at the paid rate after 12 months. Set a reminder to cancel before the renewal date if you do not want to pay.',
    guide: {
      claimSteps: [
        { title: 'Use your personal Google account', body: 'Open the official link while signed in to the Google account you want the plan on.' },
        { title: 'Verify student status', body: 'Follow the student verification prompt (handled by Google’s verification partner) with your college details.' },
        { title: 'Add a payment method', body: 'You will not be charged for 12 months, but a card or UPI mandate is required.' },
        { title: 'Set a cancel reminder', body: 'Add a calendar reminder 11 months from today to cancel if you do not want to continue.' },
      ],
      failureModes: [
        'Age outside 18–24 — the offer cannot be claimed.',
        'Verification fails with a non-academic email — use the document route if offered.',
      ],
      proTips: ['Redeem before 31 Dec 2026 — after that the offer is gone.'],
    },
  }),
  offer({
    slug: 'google-antigravity',
    name: 'Google Antigravity (agent-first IDE)',
    category: 'AI & LLM tools',
    officialUrl: 'https://antigravity.google/',
    summary: 'Google’s agent-first IDE — free for everyone during public preview.',
    whatYouGet: ['Free IDE during public preview', 'Built-in Gemini model access', 'No student verification needed'],
    eligibility: ['Anyone during the public preview'],
    status: 'changed',
    statusNote: 'Free daily request quotas have been cut several times since Dec 2025; check the current limit before relying on it.',
    indiaNote: 'Pair it with the Google AI Plus student offer for higher limits.',
  }),
  offer({
    slug: 'jetbrains-all-products',
    name: 'JetBrains Student Pack — all IDEs',
    category: 'IDEs & developer tools',
    officialUrl: 'https://www.jetbrains.com/academy/student-pack/',
    summary: 'Free educational licence for every JetBrains IDE, renewable yearly while you study.',
    whatYouGet: [
      'IntelliJ IDEA Ultimate, PyCharm Professional, WebStorm, DataGrip, Rider, CLion and more',
      'ReSharper and the other .NET tools',
      '1-year licence, renewable while enrolled',
      '40% graduation discount for 2 years after',
    ],
    valueInr: 25000,
    eligibility: [
      'Currently enrolled at a recognised institution',
      'Verify with school email, GitHub Student Pack, ISIC card or official enrolment proof',
    ],
    indiaNote: 'Verifying through the GitHub Student Pack is the most reliable route for Indian students.',
    dependsOn: [GITHUB_PACK],
    guide: {
      claimSteps: [
        { title: 'Get the GitHub Student Pack first', body: 'If your college email is not accepted, this is the fastest route.' },
        { title: 'Apply with GitHub', body: 'On the official page choose “GitHub” as the verification method and authorise JetBrains.' },
        { title: 'Activate in the IDE', body: 'Sign in with your JetBrains account inside any IDE to activate the licence.' },
      ],
      failureModes: ['Licence lapses after a year — renew from your JetBrains account while still enrolled.'],
      proTips: ['Educational licences are for non-commercial use only.'],
    },
  }),
  offer({
    slug: 'azure-for-students',
    name: 'Microsoft Azure for Students',
    category: 'Cloud credits',
    officialUrl: 'https://azure.microsoft.com/en-us/free/students',
    summary: '$100 of Azure credit for 12 months with no credit card required.',
    whatYouGet: ['$100 Azure credit for 12 months', 'A set of always-free services', 'Renewable yearly while eligible'],
    valueInr: 8000,
    eligibility: [
      '18 or older',
      'Full-time student at an accredited degree-granting institution',
      'Verify with college email, student ID upload or GitHub Education',
    ],
    indiaNote: 'No card needed — rare for a cloud offer. If your email is rejected, use GitHub verification.',
    dependsOn: [GITHUB_PACK],
    guide: {
      claimSteps: [
        { title: 'Open the official page', body: 'Click “Start free” and sign in with a Microsoft account.' },
        { title: 'Verify', body: 'Use your college email; if it is rejected, choose the GitHub or ID route.' },
        { title: 'Use the credit', body: 'Credit lasts 12 months and does not roll over. Set budget alerts in the portal.' },
      ],
      failureModes: ['One subscription per person — a second account will be blocked.'],
      proTips: ['Renew each year while you are still a student for another $100.'],
    },
  }),
  offer({
    slug: 'aws-student-pack',
    name: 'AWS Educate',
    category: 'Cloud credits',
    officialUrl: 'https://aws.amazon.com/education/awseducate/',
    summary: 'Free AWS training, hands-on labs and credits — no credit card required.',
    whatYouGet: ['600+ hours of cloud courses and labs', 'AWS credits for hands-on practice', 'Digital badges'],
    valueInr: 8000,
    eligibility: ['Students and educators (check current age and institution terms)'],
    indiaNote: 'The most accessible cloud offer for a first-year student — no card needed.',
  }),
  offer({
    slug: 'google-cloud-free-tier',
    name: 'Google Cloud free trial + Skills Boost',
    category: 'Cloud credits',
    officialUrl: 'https://cloud.google.com/free',
    summary: 'The Google Cloud free trial plus free Skills Boost labs and badges.',
    whatYouGet: [
      'Free trial credit for new Google Cloud accounts (commonly $300)',
      'Always-free product quotas',
      'Cloud Skills Boost labs and skill badges (often free via campaigns)',
    ],
    eligibility: ['New Google Cloud customers — not student-specific'],
    indiaNote: 'Watch for seasonal Google Cloud Study Jams / Arcade campaigns in India that give free lab credits and swag.',
    requiresCard: true,
    autoChargeNote:
      'A card is needed to start the trial. You are not charged when the trial ends unless you choose to upgrade to a paid account.',
  }),
  offer({
    slug: 'figma-for-education',
    name: 'Figma for Education',
    category: 'Design',
    officialUrl: 'https://www.figma.com/education/',
    summary: 'Free Figma Professional for verified higher-education students.',
    whatYouGet: ['Figma Professional plan', 'FigJam included', '~1 year term with re-verification'],
    valueInr: 15000,
    eligibility: ['Verified higher-education student or educator', 'School-issued email generally required'],
  }),
  offer({
    slug: 'notion-for-education',
    name: 'Notion for Education',
    category: 'Productivity',
    officialUrl: 'https://www.notion.com/product/notion-for-education',
    summary: 'Free Notion Plus for students with a qualifying school email.',
    whatYouGet: ['Notion Plus plan', 'Unlimited pages and blocks', '30-day version history', 'Larger file uploads'],
    valueInr: 8000,
    eligibility: ['A qualifying school email', 'Individual accounts only'],
    indiaNote: 'Thousands of non-.edu domains qualify, so try your college email even if it is not .edu.',
  }),
  offer({
    slug: 'github-copilot-students',
    name: 'GitHub Copilot for students',
    category: 'AI & LLM tools',
    officialUrl: 'https://github.com/features/copilot',
    summary: 'Free Copilot Pro for students is paused for new sign-ups.',
    whatYouGet: ['Copilot Free for new Student Pack members', 'Students verified before April 2026 keep their plan'],
    status: 'changed',
    statusNote: 'Paused for new student sign-ups since April 2026. We will notify you if it reopens.',
    dependsOn: [GITHUB_PACK],
  }),
  offer({
    slug: 'cursor-students',
    name: 'Cursor — free Pro year',
    category: 'AI & LLM tools',
    officialUrl: 'https://cursor.com/students',
    summary: 'The free student Pro year has ended for new applicants.',
    whatYouGet: [
      'Existing redeemers keep their plan until it expires',
      'Credits are still given out at Cursor campus and online events',
      'Alternatives: Zed offers verified students a free Pro year',
    ],
    status: 'ended',
    statusNote: 'Ended for new applicants on 25 June 2026.',
  }),
  offer({
    slug: 'perplexity-students',
    name: 'Perplexity for students',
    category: 'AI & LLM tools',
    officialUrl: 'https://www.perplexity.ai/',
    summary: 'The free Pro giveaway has ended; Education Pro is now offered at a student discount.',
    whatYouGet: ['Education Pro at about 50% off for verified students'],
    status: 'changed',
    statusNote: 'The free student Pro offer has expired; only the discount remains.',
    indiaNote: 'Airtel subscribers in India have had 12 months of Perplexity Pro free — check the Airtel Thanks app.',
  }),
  offer({
    slug: 'aicte-eduskills-internships',
    name: 'AICTE × EduSkills virtual internships',
    category: 'Internships',
    officialUrl: 'https://eduskillsfoundation.org/',
    summary: 'Free structured virtual internships with industry co-branded certificates.',
    whatYouGet: [
      'Guided modules, projects and assessments',
      'Certificate co-branded with the industry partner',
      'Cohorts have included Google, AWS, Microsoft and Palo Alto tracks',
    ],
    eligibility: ['UG, PG, diploma and polytechnic students', 'AICTE-affiliated or recognised colleges'],
    indiaNote: 'One of the few perks a placement cell recognises — worth more than most software licences.',
  }),
  offer({
    slug: 'nptel-swayam',
    name: 'NPTEL / SWAYAM',
    category: 'Learning & MOOCs',
    officialUrl: 'https://nptel.ac.in/',
    summary: 'Free IIT and IISc courses; the proctored certificate exam carries a fee.',
    whatYouGet: ['Free enrolment in 8- and 12-week courses', 'Optional proctored exam for a certificate', 'NPTEL internships for top performers'],
    eligibility: ['Anyone can enrol'],
    indiaNote: 'Many colleges give academic credit for NPTEL certificates — ask your department.',
  }),

  // ── Tier 2 ──────────────────────────────────────────────────────────────
  offer({
    slug: 'digitalocean-github-students',
    name: 'DigitalOcean (via GitHub Student Pack)',
    category: 'Cloud credits',
    officialUrl: 'https://www.digitalocean.com/github-students',
    summary: '$200 of DigitalOcean credit for 12 months through the Student Pack.',
    whatYouGet: ['$200 credit valid 12 months'],
    valueInr: 16000,
    statusNote: 'GPU droplets and some third-party AI services are excluded (since June 2026).',
    status: 'changed',
    requiresCard: true,
    autoChargeNote: 'A card or PayPal may be needed to activate. Destroy resources before the credit ends to avoid charges.',
    dependsOn: [GITHUB_PACK],
  }),
  offer({
    slug: 'heroku-github-students',
    name: 'Heroku (via GitHub Student Pack)',
    category: 'Hosting & infrastructure',
    officialUrl: 'https://www.heroku.com/github-students',
    summary: 'Monthly Heroku platform credits for the student term.',
    whatYouGet: ['Platform credits applied monthly'],
    valueInr: 10000,
    requiresCard: true,
    autoChargeNote: 'Heroku asks for a card. Usage above the monthly credit is billed.',
    dependsOn: [GITHUB_PACK],
  }),
  offer({
    slug: 'namecheap-github-students',
    name: 'Namecheap domain (via GitHub Student Pack)',
    category: 'Hosting & infrastructure',
    officialUrl: 'https://nc.me/',
    summary: 'One free domain for a year with SSL — .me, .dev, .app, .live and more.',
    whatYouGet: ['1 free domain for 1 year', 'SSL certificate', '25+ TLDs to choose from'],
    valueInr: 1000,
    autoChargeNote: 'Renewal after the first year is at the normal price.',
    dependsOn: [GITHUB_PACK],
  }),
  offer({
    slug: 'mongodb-atlas-students',
    name: 'MongoDB for Students',
    category: 'Cloud credits',
    officialUrl: 'https://www.mongodb.com/students',
    summary: 'Atlas credits and a free certification voucher for students.',
    whatYouGet: ['MongoDB Atlas credits', 'Free certification exam voucher (after completing the learning path)'],
    valueInr: 4000,
    dependsOn: [GITHUB_PACK],
  }),
  offer({
    slug: 'github-codespaces',
    name: 'GitHub Codespaces',
    category: 'IDEs & developer tools',
    officialUrl: 'https://github.com/features/codespaces',
    summary: 'Cloud dev environments — Pro accounts get more free hours each month.',
    whatYouGet: ['Monthly Codespaces hours and storage included with GitHub Pro'],
    dependsOn: [GITHUB_PACK],
  }),
  offer({
    slug: 'microsoft-365-education',
    name: 'Microsoft 365 for students (Office A1)',
    category: 'Productivity',
    officialUrl: 'https://www.microsoft.com/en-in/education/products/office',
    summary: 'Free web versions of Word, Excel, PowerPoint and OneNote with a school email.',
    whatYouGet: ['Office on the web', 'Teams', 'OneDrive storage set by your college'],
    eligibility: ['Valid school email from an eligible institution'],
  }),
  offer({
    slug: 'microsoft-learn',
    name: 'Microsoft Learn',
    category: 'Learning & MOOCs',
    officialUrl: 'https://learn.microsoft.com/',
    summary: 'Free learning paths, with student certification vouchers through campaigns.',
    whatYouGet: ['Free learning paths and sandboxes', 'Occasional free certification vouchers via student campaigns'],
    eligibility: ['Anyone'],
  }),
  offer({
    slug: 'canva-for-education',
    name: 'Canva for Education',
    category: 'Design',
    officialUrl: 'https://www.canva.com/education/',
    summary: 'Pro-level Canva features for eligible schools and their students.',
    whatYouGet: ['Premium templates and assets', 'Brand kits and background remover'],
    eligibility: ['Mainly school (K-12) teachers and their students — university students usually do not qualify'],
    indiaNote: 'College students should check eligibility first; Canva Pro trials are the usual fallback.',
  }),
  offer({
    slug: 'adobe-creative-cloud-students',
    name: 'Adobe Creative Cloud student plan',
    category: 'Design',
    officialUrl: 'https://www.adobe.com/in/creativecloud/plans.html',
    summary: 'All Adobe apps at a large student discount — a discount, not free.',
    whatYouGet: ['Photoshop, Illustrator, Premiere Pro and 20+ apps', 'Student pricing for the first year'],
    requiresCard: true,
    autoChargeNote: 'This is a paid plan. It renews automatically, and the price can rise after the first year.',
  }),
  offer({
    slug: 'autodesk-education',
    name: 'Autodesk Education',
    category: 'Design',
    officialUrl: 'https://www.autodesk.com/education',
    summary: 'Free 1-year educational licences for AutoCAD, Fusion, Revit and more.',
    whatYouGet: ['AutoCAD, Fusion, Revit, Maya, 3ds Max and others', '1-year licence, renewable while eligible'],
    valueInr: 150000,
    eligibility: ['Students and educators at a qualified institution', 'Proof of enrolment may be requested'],
  }),
  offer({
    slug: 'zed-students',
    name: 'Zed — free Pro year',
    category: 'IDEs & developer tools',
    officialUrl: 'https://zed.dev/',
    summary: 'A free year of Zed Pro for verified students.',
    whatYouGet: ['Zed Pro for 12 months', 'Hosted AI model usage included in Pro'],
    valueInr: 8000,
  }),
  offer({
    slug: 'kiro-students',
    name: 'Kiro — free Pro year',
    category: 'IDEs & developer tools',
    officialUrl: 'https://kiro.dev/',
    summary: 'Free Kiro Pro year for verified students — currently US and Canada only.',
    whatYouGet: ['Kiro Pro for 12 months (where available)'],
    status: 'changed',
    statusNote: 'Only available to students in the US and Canada right now — not claimable from India.',
  }),
  offer({
    slug: 'coursera-financial-aid',
    name: 'Coursera financial aid',
    category: 'Learning & MOOCs',
    officialUrl: 'https://www.coursera.org/',
    summary: 'Apply for a full fee waiver on most Coursera courses and certificates.',
    whatYouGet: ['Full course and certificate access when aid is approved', 'Audit option for free learning'],
    eligibility: ['Anyone can apply; approval takes about two weeks'],
  }),
  offer({
    slug: 'edx-audit',
    name: 'edX audit track',
    category: 'Learning & MOOCs',
    officialUrl: 'https://www.edx.org/',
    summary: 'Audit university courses for free; certificates are paid.',
    whatYouGet: ['Free access to course material on the audit track'],
    eligibility: ['Anyone'],
  }),
  offer({
    slug: 'google-career-certificates',
    name: 'Google Career Certificates',
    category: 'Certifications',
    officialUrl: 'https://grow.google/certificates/',
    summary: 'Job-ready certificates, with scholarships and campaign-based free access in India.',
    whatYouGet: ['Data analytics, UX, IT support, project management and more', 'Scholarship routes through Indian partner programmes'],
    eligibility: ['Anyone; scholarships have their own criteria'],
  }),
  offer({
    slug: 'freecodecamp',
    name: 'freeCodeCamp',
    category: 'Learning & MOOCs',
    officialUrl: 'https://www.freecodecamp.org/',
    summary: 'A free full-stack curriculum with verified certifications.',
    whatYouGet: ['Thousands of hours of lessons', 'Free verified certifications'],
    eligibility: ['Anyone'],
  }),
  offer({
    slug: 'cs50-harvard',
    name: 'CS50 (Harvard)',
    category: 'Learning & MOOCs',
    officialUrl: 'https://cs50.harvard.edu/',
    summary: 'Harvard’s intro to computer science, free online.',
    whatYouGet: ['Full course with problem sets', 'Free CS50 certificate; paid verified certificate optional'],
    eligibility: ['Anyone'],
  }),
  offer({
    slug: 'kaggle',
    name: 'Kaggle',
    category: 'AI & LLM tools',
    officialUrl: 'https://www.kaggle.com/',
    summary: 'Free GPU and TPU notebook hours, datasets, courses and competitions.',
    whatYouGet: ['Weekly free GPU/TPU quota', 'Datasets and competitions', 'Free micro-courses'],
    eligibility: ['Anyone (phone verification needed for GPU)'],
  }),
  offer({
    slug: 'hugging-face',
    name: 'Hugging Face',
    category: 'AI & LLM tools',
    officialUrl: 'https://huggingface.co/',
    summary: 'Free model and dataset hosting, plus Spaces to demo your projects.',
    whatYouGet: ['Free Spaces on CPU hardware', 'Model and dataset hosting', 'Inference credits on the free tier'],
    eligibility: ['Anyone'],
  }),
  offer({
    slug: 'google-colab',
    name: 'Google Colab',
    category: 'AI & LLM tools',
    officialUrl: 'https://colab.research.google.com/',
    summary: 'Free Jupyter notebooks with GPU sessions in the browser.',
    whatYouGet: ['Free GPU sessions (subject to availability)', 'Google Drive integration'],
    eligibility: ['Anyone with a Google account'],
  }),
  offer({
    slug: 'unstop',
    name: 'Unstop',
    category: 'Hackathons & competitions',
    officialUrl: 'https://unstop.com/',
    summary: 'Free hackathons, case competitions, quizzes and internships across India.',
    whatYouGet: ['Competitions with cash prizes and PPIs', 'Internship and job listings'],
    eligibility: ['Students in India'],
  }),
  offer({
    slug: 'devfolio',
    name: 'Devfolio',
    category: 'Hackathons & competitions',
    officialUrl: 'https://devfolio.co/',
    summary: 'India’s hackathon hub — prizes, sponsor credits and perks.',
    whatYouGet: ['Hackathons across India', 'Sponsor credits and swag for participants'],
    eligibility: ['Anyone; individual hackathons set their own rules'],
  }),
  offer({
    slug: 'smart-india-hackathon',
    name: 'Smart India Hackathon',
    category: 'Hackathons & competitions',
    officialUrl: 'https://sih.gov.in/',
    summary: 'Government-run national hackathon with strong resume value.',
    whatYouGet: ['Real problem statements from ministries and industry', 'Cash prizes for winners'],
    eligibility: ['Teams nominated through their college'],
    indiaNote: 'Registration runs through your college SPOC — ask your department early.',
  }),
  offer({
    slug: 'internshala',
    name: 'Internshala',
    category: 'Internships',
    officialUrl: 'https://internshala.com/',
    summary: 'Free internship listings across India, plus paid trainings.',
    whatYouGet: ['Free internship and fresher job listings', 'Optional paid trainings'],
    eligibility: ['Students in India'],
  }),
  offer({
    slug: 'microsoft-learn-student-ambassadors',
    name: 'Microsoft Learn Student Ambassadors',
    category: 'Ambassador programs',
    officialUrl: 'https://studentambassadors.microsoft.com/',
    summary: 'Microsoft’s student community — perks, mentorship and certification vouchers.',
    whatYouGet: ['Certification vouchers', 'Azure credits and swag', 'Mentorship and events'],
    eligibility: ['16+ and enrolled in an academic institution'],
  }),
  offer({
    slug: 'gdg-on-campus',
    name: 'Google Developer Groups on Campus',
    category: 'Communities',
    officialUrl: 'https://developers.google.com/community/gdsc',
    summary: 'Campus developer clubs backed by Google — events, credits and mentorship.',
    whatYouGet: ['Workshops and Study Jams', 'Cloud credits at events', 'Organizer programme for leads'],
    eligibility: ['University students'],
  }),
  offer({
    slug: 'github-campus-experts',
    name: 'GitHub Campus Experts',
    category: 'Ambassador programs',
    officialUrl: 'https://githubcampus.expert/',
    summary: 'GitHub’s student leader programme — training, swag and resources.',
    whatYouGet: ['Community leadership training', 'Event support and swag'],
    eligibility: ['18+ students with the GitHub Student Pack'],
    dependsOn: [GITHUB_PACK],
  }),
  offer({
    slug: 'postman-student-program',
    name: 'Postman Student Program',
    category: 'Certifications',
    officialUrl: 'https://www.postman.com/student-program/',
    summary: 'Free Postman Student Expert certification and the student leader programme.',
    whatYouGet: ['Postman Student Expert badge', 'Student Leader programme'],
  }),
  offer({
    slug: 'twilio-sendgrid-credits',
    name: 'Twilio and SendGrid credits',
    category: 'Cloud credits',
    officialUrl: 'https://www.twilio.com/',
    summary: 'Trial credits, plus extra credits through the Student Pack and hackathons.',
    whatYouGet: ['Trial credit on sign-up', 'Hackathon and Student Pack credits'],
    dependsOn: [GITHUB_PACK],
  }),
  offer({
    slug: 'vercel-hobby',
    name: 'Vercel Hobby',
    category: 'Hosting & infrastructure',
    officialUrl: 'https://vercel.com/',
    summary: 'Free hosting for personal and student projects.',
    whatYouGet: ['Free deployments with HTTPS', 'Serverless functions quota', 'Preview deployments'],
    eligibility: ['Anyone, for non-commercial use'],
  }),
  offer({
    slug: 'netlify-free',
    name: 'Netlify free plan',
    category: 'Hosting & infrastructure',
    officialUrl: 'https://www.netlify.com/',
    summary: 'Free static hosting with functions and forms.',
    whatYouGet: ['Static hosting with HTTPS', 'Functions and forms quota'],
    eligibility: ['Anyone'],
  }),
  offer({
    slug: 'cloudflare-free',
    name: 'Cloudflare free plan',
    category: 'Hosting & infrastructure',
    officialUrl: 'https://www.cloudflare.com/',
    summary: 'Free CDN, DNS, Pages hosting and a Workers quota.',
    whatYouGet: ['CDN and DNS', 'Cloudflare Pages', 'Workers free quota'],
    eligibility: ['Anyone'],
  }),
  offer({
    slug: 'supabase-firebase-free',
    name: 'Supabase and Firebase free tiers',
    category: 'Hosting & infrastructure',
    officialUrl: 'https://supabase.com/',
    summary: 'Free database, auth and storage quotas for your projects.',
    whatYouGet: ['Supabase free projects (Postgres, auth, storage)', 'Firebase Spark plan (firebase.google.com)'],
    eligibility: ['Anyone'],
  }),
  offer({
    slug: 'jetbrains-academy',
    name: 'JetBrains Academy (Hyperskill)',
    category: 'Learning & MOOCs',
    officialUrl: 'https://hyperskill.org/',
    summary: 'Project-based learning tracks, free or discounted for students.',
    whatYouGet: ['Project-based tracks in Python, Java, Kotlin and more'],
    dependsOn: ['jetbrains-all-products'],
  }),
  offer({
    slug: 'linkedin-learning-institutional',
    name: 'LinkedIn Learning via your college',
    category: 'Learning & MOOCs',
    officialUrl: 'https://www.linkedin.com/learning/',
    summary: 'Many colleges and libraries give free LinkedIn Learning access.',
    whatYouGet: ['Full course library through an institutional login'],
    eligibility: ['Students whose college or library has a licence'],
    indiaNote: 'Ask your college library or placement cell whether you have an institutional login.',
  }),
  offer({
    slug: 'isic-card-india',
    name: 'ISIC student card (India)',
    category: 'Hardware & discounts',
    officialUrl: 'https://www.isicindia.com/',
    summary: 'A paid international student ID that unlocks verification elsewhere.',
    whatYouGet: ['Internationally recognised student ID', 'Accepted for JetBrains and other verifications', 'Travel and retail discounts'],
    indiaNote: 'The cheap unlock for students without an institutional email. It costs money — buy it only if other routes fail.',
  }),
  offer({
    slug: 'nvidia-dli',
    name: 'NVIDIA Deep Learning Institute',
    category: 'Learning & MOOCs',
    officialUrl: 'https://www.nvidia.com/dli',
    summary: 'Free self-paced AI courses and occasional free workshop credits.',
    whatYouGet: ['Free self-paced courses', 'Workshop credits through university programmes'],
    eligibility: ['Anyone; some courses are paid'],
  }),
  offer({
    slug: 'oracle-salesforce-redhat-academies',
    name: 'Oracle, Salesforce and Red Hat academies',
    category: 'Certifications',
    officialUrl: 'https://education.oracle.com/',
    summary: 'Free learning tracks and discounted certifications from enterprise vendors.',
    whatYouGet: ['Oracle University free tracks', 'Salesforce Trailhead (trailhead.salesforce.com)', 'Red Hat Academy through member colleges'],
    eligibility: ['Anyone; academy programmes need a member college'],
  }),
  offer({
    slug: 'aicte-neat',
    name: 'AICTE free internships and NEAT',
    category: 'Learning & MOOCs',
    officialUrl: 'https://www.aicte-india.org/',
    summary: 'Government-backed internships and ed-tech courses, free for eligible students.',
    whatYouGet: ['AICTE internship portal', 'NEAT courses with free seats for economically weaker students'],
    eligibility: ['Students at AICTE-approved institutions'],
  }),
  offer({
    slug: 'national-scholarship-portal',
    name: 'National Scholarship Portal (NSP)',
    category: 'Scholarships & funding',
    officialUrl: 'https://scholarships.gov.in/',
    summary: 'Central and state scholarships in one place — deadlines matter.',
    whatYouGet: ['Central, state and UGC scholarships', 'One application for many schemes'],
    eligibility: ['Indian students; each scheme has its own income and merit criteria'],
    indiaNote: 'Applications usually open mid-year and close within weeks. Keep income and caste certificates ready.',
  }),
]
